from typing import List
from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    session_id: str = Field(
        ...,
        description="Session identifier for the chat",
    )
    answer: str = Field(
        ...,
        description="Final answer generated by the assistant",
    )
    sources: List[str] = Field(
        default_factory=list,
        description="Source document identifiers used for the answer",
    )